### ISSUE TITLE
[feature request] add option to send notifications on mention

### ISSUE THREAD

**Issue by ayushnix** [glguy/irc-core#107]
Hi!

I mentioned this before on the `#glirc` IRC channel but I'd like to open a feature request so that this can be tracked.

I'm enjoying using glric right now but if anyone mentions me on IRC, I don't get to know about it unless I switch to glirc (maybe hours later) and explicitly use `/mentions`. It would be nice if glirc can be configured to use a command to send notifications containing the message text in a mention.

**Comment by glguy** [comment]
Notes from my snowcone implemention:

* incorporate into /ignore
* Don't notify on history playback
* maybe don't notify when focused
* notify once per user or pet event, not sure, on defocus
* this probably replaces and extends the terminal bell notification - maybe we want both simultaneously?
* Terminal-notifier on Mac has a weird quirk requiring a leading backslash in the message in some cases.
* don't block the client waiting for the command to finish executing

**Comment by ayushnix** [comment]
> maybe don't notify when focused

If this is considered, I'd advise that the implementation should be configurable. Although I like how glirc highlights the window character using the red color to indicate a mention, relying on color alone is not adequate. Some users may not have colors enabled and some users are color-blind so they may not realize someone has mentioned them even if glirc is in focus.

**Comment by ayushnix** [comment]
This might be a nice-to-have (but not essential) addition but maybe some channels and users can be muted to not show notifications, even when notifications are configured globally for other channels.

**Comment by glguy** [comment]
The current implementation will process as many irc messages as are available accumulating terminal bell to only bell once per batch. 

@TheDaemoness already had code for adding more noise levels to windows, so I imagine that per window settings are in mind

**Comment by TheDaemoness** [comment]
I've been summoned!

> incorporate into /ignore

My plan is to only notify on "important" messages, while also having a noise level that upgrades normal messages to important messages (see `/setwindow louder` in the notify branch).
Messages from people who are /ignored are "boring" so in theory this should be fine.

> maybe don't notify when focused

Already added a `Bool` to `ClientState` for this (not yet pushed).
I need to look into whether we send the control sequence for the terminal emulator to send us these events.

> notify once per user or pet event, not sure, on defocus

I'm thinking "once per window since defocus".

> Don't notify on history playback

This means setting a variable to suppress notifications during playback, which means identifying the start and end of playback. Doable, but will take some research on my part.

That said, if we don't notify when focused, only notify once per window, and assume that history playback usually occurs while focused, maybe we don't need to do anything special here?

> this probably replaces and extends the terminal bell notification - maybe we want both simultaneously?

Both would be nice. Maybe the bell could still be sent regardless of focus state?

> Terminal-notifier on Mac has a weird quirk requiring a leading backslash in the message in some cases.

Good to know, though do we want to fall back to an external dependency here?

>  don't block the client waiting for the command to finish executing

We can just spawn the notification command and not wait for it to finish. We don't care about its output or exit code really.
