### ISSUE TITLE
Collapse repeated AWAY messages

### ISSUE THREAD

**Issue by glguy** [glguy/irc-core#72]

**Comment by swantzter** [comment]
Perhaps it could also be shown in the window with that user rather than in the status window?

**Comment by glguy** [comment]
I agree that these message are annoying. (Why do people stay on away while they are talking to me???)

Putting them into the query window makes sense, but I don't want to see them cluttering up the query window after every message.

I think I'd like to collapse them down to a "metadata" `A` entry, but that will just result in a bunch of extra A lines in the query window. If I kept them in the server status they'd collapse but continue to be rather unuseful.

I could just hide them. I'm looking for good ideas.

**Comment by swantzter** [comment]
I was thinking adding an "away" line to the users buffer when you first send them a message and they're away, and then send an "unaway" line once you send them a message and they're no longer away.

Alternatively a marker next to the nick? For example action bar `(Y:fn:glguy (away))` or something like that? That could also use `away-notify` to update

(as for your question, because I'm not _supposed_ to be on irc at the time!)
