### ISSUE TITLE
invites do not generate notifications

### ISSUE THREAD

**Issue by SimonMarechal** [glguy/irc-core#94]
Hi! I wondered if this was something I missed, but invites do not generate notifications, so it is often the case that I do not realize I have been invited to a channel. Is there a configuration for that?

**Comment by glguy** [comment]
Hi, invite messages go to the server console, but unsolicited invites aren't made prominent by the client. Ideally if you're getting invited to a channel it was because you were expecting to receive the invite. For the spam case they'll just show up as a message in the server console without a lot of fanfare

**Comment by SimonMarechal** [comment]
Right, I only use it on private servers so I did not think about spam, this makes a lot of sense!
