### ISSUE TITLE
M-PageUp and M-PageDown do not work

### ISSUE THREAD

**Issue by subnut** [glguy/irc-core#97]
### Terminals tested: 
- foot (https://codeberg.org/dnkl/foot)
- alacritty (https://github.com/alacritty/alacritty)
- kitty (https://github.com/kovidgoyal/kitty)

### Escape code produced
- <kbd>Meta</kbd>+<kbd>Page Up</kbd>
  ```
  ^[[5;3~
  ```

- <kbd>Meta</kbd>+<kbd>Page Down</kbd>
  ```
  ^[[6;3~
  ```

**Comment by subnut** [comment]
### Temporary workaround
Create/Append to `~/.vty/config`
```
map "foot" "\ESC[5;3~" KPageUp [MMeta]
map "foot" "\ESC[6;3~" KPageDown [MMeta]
```
where `foot` is the value of `$TERM`  

Create the above entries for all the concerned terminals' `$TERM` values

---

@glguy I think this issue can be closed if you think that this should be fixed upstream (in the vty library that glirc is using)

**Comment by glguy** [comment]
I think this is already fixed upstream. Are you using an outdated package from a distro package manager or something built with `cabal`?

**Comment by subnut** [comment]
Built by cabal. glirc hasn't been packaged for Void Linux, it seems.

How to re-build?

**Comment by glguy** [comment]
These bindings were added to vty here: https://github.com/jtdaugherty/vty/commit/27e9bf77a54fd27596ad86423c33054e6077811f

So that'd mean the fix is available in versions [5.34](https://github.com/jtdaugherty/vty/releases/tag/5.34)  [5.33](https://github.com/jtdaugherty/vty/releases/tag/5.33) [5.32](https://github.com/jtdaugherty/vty/releases/tag/5.32)

Make sure your cabal-install binary is up-to-date: `3.6.2.0`. By default cabal will use one of these versions to build glirc, but if yours isn't for some reason you can encourage it with: `cabal install "--constraint=vty>=5.32"`

**Comment by subnut** [comment]
Ah, well, that commit adds support for `"\ESC\ESC[5~"`, but the escape code emitted by the tested terminals is `"\ESC[5;3~"`

**Comment by glguy** [comment]
`"\ESC[5;3~"` is just regular Page Up. The extra `\ESC` is what makes it Meta-PageUp

**Comment by subnut** [comment]
Nope, in the terminals mentioned in the OP, `"\ESC[5~"` is the regular Page Up, and `"\ESC[5;3~"` is the Meta-PageUp :upside_down_face:

**Comment by subnut** [comment]
Ah, looks like I found the source of all this drama -  
https://sw.kovidgoyal.net/kitty/keyboard-protocol

**Comment by subnut** [comment]
Closing because it is an upstream issue in jtdaugherty/vty
